### ISSUE TITLE
可以启动下这个前后端的演示程序么?谢谢

### ISSUE THREAD

**Issue by JadenGao** [sunburst89757/react-admin#1]
可以启动下这个前后端的演示程序么?谢谢
https://github.com/sunburst89757/react-admin-backend

**Comment by sunburst89757** [comment]
你可以参见下https://github.com/sunburst89757/koa-ts-template/tree/general的使用说明
总的来说 你需要先配置两个文件  一个是keys 一个是.env 环境变量管理

1. 配置keys文件夹下的公私钥 这个是用来加密用户密码
2. 配置mySQL环境变量  见链接里的prisma
3. 配置redis环境变量 见链接https://github.com/redis/node-redis

![image](https://user-images.githubusercontent.com/82217593/224224713-531b130e-dbf3-4b06-8b14-6d199e89f381.png)
![image](https://user-images.githubusercontent.com/82217593/224224790-b01b53fd-862f-4521-91a0-1b869b6ff302.png)
